import { MovieProvider } from "@/context/MovieContext";

import "@/app/globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <MovieProvider>
          {children}
        </MovieProvider>
      </body>
    </html>
  );
}
